#pragma once


#define DEF_MAX_SPRITES 40000
#define DEF_VERTEX_SIZE sizeof(BufferData)
#define DEF_SPRITE_SIZE	DEF_VERTEX_SIZE * 4

#define DEF_BUFFER_SIZE DEF_SPRITE_SIZE * DEF_MAX_SPRITES
#define DEF_INDICES_SIZE DEF_MAX_SPRITES * 6

#define DEF_VERTEX_POSITION_INDEX 0
#define DEF_VERTEX_COLOR_INDEX 1
